Django2YingOps/Django2YingOps/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from Django2YingOps.settings import MEDIA_ROOT

import xadmin
from users.views import *
from assets.views import *

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    # include urls
    path('users/',include('users.urls')),
    path('assets/',include('assets.urls')),

    path('',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('index/',IndexView.as_view(),name='index'),
    path('register/',RegisterView.as_view(),name='register'),
    path('forget/',ForgetPwdView.as_view(),name='forget'),

    #配置上传文件的访问处理函数
    re_path('media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),
]

Django2YingOps/apps/assets/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt

from users.views import *
from assets.views import *


app_name = 'assets'
urlpatterns = [
    # path('admin/', admin.site.urls),
    # 初始化资产
    path('init/', AssetsInit.as_view(),name='assets_init'),
    # 资产列表
    path('list/', AssetsListView.as_view(),name='assets_list'),
    # 资产API
    path('listapi/', AssetsListApiView.as_view(),name='assets_listapi'),
    # 资产详情
    path('detail/<int:id>', AssetsDetailView.as_view(),name='assets_detail'),
    # 资产在线状态
    path('live_status/', csrf_exempt(AssetsLiveStatuslView.as_view()),name='assets_live_status'),
    # 资产全部更新
    path('updateassets/', csrf_exempt(UpdateAllAssetsView.as_view()),name='assets_update_all'),
    # 导出资产
    path('excleexport/', AssetsExportView.as_view(), name='assets_excle_export'),
    # webssh
    path('websshs/', AssetsWebSshsView.as_view(),name='assets_webssh'),
    # ipscan
    path('ipscan/', IpScanView.as_view(),name='assets_ipscan'),

    # ibm_status
    path('ibm_status/', csrf_exempt(IbmStatusView.as_view()),name='ibm_status'),


]

Django2YingOps/apps/assets/models.py
# coding:utf8
from django.db import models
from django.utils.translation import ugettext_lazy as _, ugettext


# Create your models here.
class ComputerRoom(models.Model):
    name = models.CharField(max_length=64, null=True, blank=True, verbose_name=u'机房名称', default='')

    class Meta:
        verbose_name = u'机房表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class AssetsInfo(models.Model):
    ip = models.CharField(max_length=32,null=True, blank=True, verbose_name=u"主机IP信息", default="")
    hostname = models.CharField(max_length=32, null=True, blank=True, verbose_name=u"操作系统主机名", default="")
    cpu_cores = models.CharField(max_length=32, null=True, blank=True, verbose_name=u"cpu核数", default="")
    mem_total = models.CharField(max_length=32, null=True, blank=True, verbose_name=u"内存总大小", default="")
    disk_total = models.CharField(max_length=32, null=True, blank=True, verbose_name=u"磁盘总大小", default="")
    cpu_status = models.CharField(max_length=32, null=True, blank=True, verbose_name=u"cpu使用率", default="")
    mem_status = models.CharField(max_length=32, null=True, blank=True, verbose_name=u"内存使用率", default="")
    disk_status = models.CharField(max_length=32, null=True, blank=True, verbose_name=u"磁盘使用率", default="")
    system_time = models.CharField(max_length=32, null=True, blank=True, verbose_name=u"系统当前时间", default="")
    up_time = models.CharField(max_length=32, null=True, blank=True, verbose_name=u"系统运行时间", default="")
    system_ver = models.CharField(max_length=256, null=True, blank=True, verbose_name=u"操作系统版本", default="系统版本")
    mac_address = models.CharField(max_length=64, null=True, blank=True, verbose_name=u"mac地址", default="")
    sn = models.CharField(max_length=64, null=True, blank=True, verbose_name=u"SN－主机的唯一标示", default="Unknow")
    manufacturer = models.CharField(max_length=256, null=True, blank=True, verbose_name=u"制造商", default="Unknow")
    product = models.CharField(max_length=256, null=True, blank=True, verbose_name=u"型号", default="Unknow")
    cpu_info = models.CharField(max_length=100, null=True, blank=True, verbose_name=u"cpu型号", default="")
    is_online = models.BooleanField(verbose_name=u'状态',default=True)
    is_delete = models.BooleanField(verbose_name=u'是否删除',default=False)
    desc = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'描述信息', default="Unknow")
    computer_room = models.ForeignKey(ComputerRoom, on_delete=models.CASCADE, verbose_name=u"所在机房", default=1)
    ssh_port = models.CharField(max_length=32, null=True, blank=True, verbose_name=u"ssh登录的端口", default="")
    ssh_user = models.CharField(max_length=32, null=True, blank=True, verbose_name=u"ssh登录的用户", default="")
    ssh_passwd = models.CharField(max_length=64, null=True, blank=True, verbose_name=u"ssh登录的密码", default="")

    class Meta:
        verbose_name = u'资产信息表'
        verbose_name_plural = verbose_name

        def __str__(self):
            return self.ip

class IbmStatus(models.Model):
    ip = models.CharField(max_length=64, null=True, verbose_name=u"IMM接口IP", default="")
    Processors = models.CharField(max_length=64, null=True, verbose_name=u"处理器", default="")
    Disks = models.CharField(max_length=64, null=True, verbose_name=u"磁盘", default="")
    System = models.CharField(max_length=64, null=True, verbose_name=u"操作系统", default="")
    Memory = models.CharField(max_length=64, null=True, verbose_name=u"内存", default="")
    Power_Modules = models.CharField(max_length=64, null=True, verbose_name=u"电源模块", default="")
    Cooling_Devices = models.CharField(max_length=64, null=True, verbose_name=u"风扇", default="")
    Adapters = models.CharField(max_length=64, null=True, verbose_name=u"适配器", default="")
    date_time = models.CharField(max_length=64, null=True, verbose_name=u"更新时间", default="")

    class Meta:
        verbose_name = u'IBM服务器状态表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ip

Django2YingOps/apps/assets/views.py
import re, json, os, base64, datetime
from django.shortcuts import render, HttpResponse, redirect
from django.views.generic import View
from .models import *

from Django2YingOps.settings import WSSH_IP
from utils.nmap_assets import GetLinuxMethod
from utils.mixin_util import LoginRequiredMixin
from utils.ibmstatus import getIbmList
from utils.ipscan import ScanHosts
import xlwt
from io import BytesIO


# 初始化资产/新增资产
class AssetsInit(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'assets/init.html', locals())

    def post(self, request):
        nets = re.split('\;|\；', request.POST.get('nets', '').strip())
        user_list = re.split('\;|\；', request.POST.get('user_list', '').strip())
        port_list = re.split('\;|\；', request.POST.get('port_list', '').strip())
        passwd_list = re.split('\;|\；', request.POST.get('passwd_list', '').strip())
        # port_list = [int(port) for port in port_list]
        # print(nets, user_list, port_list, passwd_list)
        # nets = '192.168.5.155'
        glm = GetLinuxMethod()
        linux_list = glm.get_linux_list(nets)
        assets_dict = glm.try_ssh_login(linux_list, user_list, port_list, passwd_list)
        if not assets_dict:
            return render(request, 'assets/init.html', {'msg': '{0}密码错误，添加失败！'.format(nets[0])})
        for ip, values in assets_dict.items():
            # print('------>', '进来了呢' )
            try:
                assets_info = AssetsInfo.objects.get(ip=values[3])
                pass
            except Exception as e:
                assets_info = AssetsInfo()
                assets_info.ssh_user = values[0]
                assets_info.ssh_passwd = values[1]
                assets_info.ssh_port = values[2]
                assets_info.ip = values[3]
                assets_info.hostname = values[4]
                assets_info.cpu_cores = values[5]
                assets_info.mem_total = values[6]
                assets_info.disk_total = values[7]
                assets_info.cpu_status = values[8]
                assets_info.mem_status = values[9]
                assets_info.disk_status = values[10]
                assets_info.system_time = values[11]
                assets_info.up_time = values[12]
                assets_info.system_ver = values[13]
                assets_info.mac_address = values[14]
                assets_info.sn = values[15]
                assets_info.manufacturer = values[16]
                assets_info.product = values[17]
                assets_info.cpu_info = values[18]
                assets_info.save()
            # print('新增资产：{0} 成功'.format(ip))
        return redirect('assets:assets_list')


# 资产API
class AssetsListApiView(View):
    def get(self, request):
        obj = AssetsInfo.objects.all()
        assets_info = {}
        for i in obj:
            tmp_dict = {}
            tmp_dict['ip'] = i.ip
            tmp_dict['hostname'] = i.hostname
            tmp_dict['cpu_status'] = i.cpu_status
            tmp_dict['mem_status'] = i.mem_status
            tmp_dict['disk_status'] = i.disk_status
            tmp_dict['sn'] = i.sn
            tmp_dict['up_time'] = i.up_time
            assets_info[i.ip] = tmp_dict
        return HttpResponse(json.dumps(assets_info))


# 资产列表
class AssetsListView(LoginRequiredMixin, View):
    def get(self, request):
        obj = AssetsInfo.objects.filter(is_delete=False).all()
        return render(request, 'assets/linux.html', locals())

    def post(self, request):
        # 删除资产
        ip = request.POST.get('delip').strip()
        AssetsInfo.objects.filter(ip=ip).update(is_delete=True)
        return HttpResponse('delok')


# 资产当前状态获取
class AssetsLiveStatuslView(View):
    # 详情页刷新资产信息
    def get(self, request):
        try:
            ip = request.GET.get('ip', '').strip()
            obj = AssetsInfo.objects.filter(ip=ip).first()
            linux_list = [ip]
            user_list = [obj.ssh_user]
            port_list = [obj.ssh_port]
            passwd_list = [obj.ssh_passwd]
            glm = GetLinuxMethod()
            assets_dict = glm.try_ssh_login(linux_list, user_list, port_list, passwd_list)
            update_dict = {}
            for ip, values in assets_dict.items():
                update_dict['hostname'] = values[4]
                update_dict['cpu_cores'] = values[5]
                update_dict['mem_total'] = values[6]
                update_dict['disk_total'] = values[7]
                update_dict['cpu_status'] = values[8]
                update_dict['mem_status'] = values[9]
                update_dict['disk_status'] = values[10]
                update_dict['system_time'] = values[11]
                update_dict['up_time'] = values[12]
                update_dict['system_ver'] = values[13]
                update_dict['mac_address'] = values[14]
                update_dict['sn'] = values[15]
                update_dict['manufacturer'] = values[16]
                update_dict['product'] = values[17]
                update_dict['cpu_info'] = values[18]
            # print(update_dict)
            AssetsInfo.objects.filter(ip=ip).update(**update_dict)
            return HttpResponse('刷新成功')
        except Exception:
            return HttpResponse('刷新失败')

    # agent定时更新资产信息
    def post(self, request):
        try:
            ip = request.POST.get('ip', '')
            # print('------>',ip)
            if AssetsInfo.objects.get(ip=ip):
                assets_dict = {}
                assets_dict['hostname'] = request.POST.get('hostname', '')
                assets_dict['cpu_cores'] = request.POST.get('cpu_cores', '')
                assets_dict['mem_total'] = request.POST.get('mem_total', '')
                assets_dict['disk_total'] = request.POST.get('disk_total', '')
                assets_dict['cpu_status'] = request.POST.get('cpu_status', '')
                assets_dict['mem_status'] = request.POST.get('mem_status', '')
                assets_dict['disk_status'] = request.POST.get('disk_status', '')
                assets_dict['system_time'] = request.POST.get('system_time', '')
                assets_dict['up_time'] = request.POST.get('up_time', '')
                assets_dict['system_ver'] = request.POST.get('system_ver', '')
                assets_dict['mac_address'] = request.POST.get('mac_address', '')
                assets_dict['sn'] = request.POST.get('sn', '')
                assets_dict['manufacturer'] = request.POST.get('manufacturer', '')
                assets_dict['product'] = request.POST.get('product', '')
                assets_dict['cpu_info'] = request.POST.get('cpu_info', '')
                # print('assets_dict', assets_dict)
                AssetsInfo.objects.filter(ip=ip).update(**assets_dict)
                return HttpResponse('update ok \n')
                # assets_info.hostname = request.POST.get('ip','')
        except Exception:
            return HttpResponse('post error ...\n')
        # except Exception:
        #     assets_info = AssetsInfo()
        #     assets_info.hostname = request.POST.get('ip','')
        #     assets_info.hostname = request.POST.get('hostname','')
        #     assets_info.cpu_cores = request.POST.get('cpu_cores','')
        #     assets_info.mem_total = request.POST.get('mem_total','')
        #     assets_info.disk_total = request.POST.get('disk_total','')
        #     assets_info.cpu_status = request.POST.get('cpu_status','')
        #     assets_info.mem_status = request.POST.get('mem_status','')
        #     assets_info.disk_status = request.POST.get('disk_status','')
        #     assets_info.system_time = request.POST.get('system_time','')
        #     assets_info.up_time = request.POST.get('v','')
        #     assets_info.system_ver = request.POST.get('system_ver','')
        #     assets_info.mac_address = request.POST.get('mac_address','')
        #     assets_info.sn = request.POST.get('sn','')
        #     assets_info.manufacturer = request.POST.get('manufacturer','')
        #     assets_info.product = request.POST.get('product','')
        #     assets_info.cpu_info = request.POST.get('cpu_info','')
        #     assets_info.save()


# 一键更新全部资产信息
class UpdateAllAssetsView(View):
    def post(self, request):
        obj = AssetsInfo.objects.all()
        for i in obj:
            linux_list = [i.ip]
            user_list = [i.ssh_user]
            port_list = [i.ssh_port]
            passwd_list = [i.ssh_passwd]
            glm = GetLinuxMethod()
            assets_dict = glm.try_ssh_login(linux_list, user_list, port_list, passwd_list)
            update_dict = {}
            for ip, values in assets_dict.items():
                update_dict['hostname'] = values[4]
                update_dict['cpu_cores'] = values[5]
                update_dict['mem_total'] = values[6]
                update_dict['disk_total'] = values[7]
                update_dict['cpu_status'] = values[8]
                update_dict['mem_status'] = values[9]
                update_dict['disk_status'] = values[10]
                update_dict['system_time'] = values[11]
                update_dict['up_time'] = values[12]
                update_dict['system_ver'] = values[13]
                update_dict['mac_address'] = values[14]
                update_dict['sn'] = values[15]
                update_dict['manufacturer'] = values[16]
                update_dict['product'] = values[17]
                update_dict['cpu_info'] = values[18]
                # print(update_dict)
            AssetsInfo.objects.filter(ip=i.ip).update(**update_dict)
        return HttpResponse('更新成功')


# 资产详情
class AssetsDetailView(LoginRequiredMixin, View):
    def get(self, request, id):
        obj = AssetsInfo.objects.filter(id=id).first()
        return render(request, 'assets/detail.html', locals())

    def post(self, request):
        pass


# webssh远程连接
class AssetsWebSshsView(View):
    def get(self, request):
        url = "http://{0}/?".format(WSSH_IP)

Django2YingOps/templates/assets/ibmstatus.html
{% extends 'base.html' %}

{% block title %}
    资产信息-IBM服务器状态
{% endblock %}
{% block zcopen %}class="active open"{% endblock %}
{% block ibmsactive %}class="active"{% endblock %}
{% block content %}
    <div class="main-content">
        <ul class="breadcrumb">
            <li>
                <i class="icon-home home-icon"></i>
                <a href="{% url 'index' %}">首页</a>
            </li>

            <li>
                <a href="#">资产信息</a>
            </li>
            <li class="active">IBM服务器状态</li>
        </ul><!-- .breadcrumb -->

        <div class="page-content">
            <div class="page-header">
                <button id="ibm_status_update" class="btn btn-app btn-primary icon-refresh ibm_status_update">更新数据</button>
            </div>
        {% load  my_filter %}
        <div class="row">
            {% for i in obj %}
                <div class="col-xs-12 col-sm-2" >
                    <div class="widget-box ">
                        <div class="widget-header">
                            {% if i.System == 'Normal'  and i.Disks == 'Normal'  and i.Processors == 'Normal'  and i.Memory == 'Normal'  and i.Power_Modules == 'Normal'    and i.Cooling_Devices == 'Normal'    and i.Adapters == 'Normal'  %}
                                <h4 style="color: #2e8965"><a href="https://{{ i.ip }}" target="_blank">{{ i.ip }}</a></h4>
                            {% else %}
                                <h4 style="color: red"><a href="https://{{ i.ip }}" target="_blank">{{ i.ip }}</a></h4>
                            {% endif %}
                        </div>
                        <div class="widget-body">
                            <div class="widget-main">
                                <div class="" id="navbar">
                                    <div style="height: 170px;">
                                        <div>处理器: <span >{{ i.Processors|replace_str }}</span></div>
                                        <div>磁盘: <span>{{ i.Disks|replace_str }}</span></div>
                                        <div>系统: <span>{{ i.System|replace_str }}</span></div>
                                        <div>内存: <span>{{ i.Memory|replace_str }}</span></div>
                                        <div>电源: <span>{{ i.Power_Modules|replace_str }}</span></div>
                                        <div>风扇: <span>{{ i.Cooling_Devices|replace_str }}</span></div>
                                        <div>适配器: <span>{{ i.Adapters|replace_str }}</span></div>
                                        <div>更新时间: <span>{{ i.date_time }}</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script src="/static/assets/js/bootstrap.min.js"></script>
    <script src="/static/assets/js/typeahead-bs2.min.js"></script>
    <script src="/static/assets/js/chosen.jquery.min.js"></script>
    <script src="/static/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="/static/assets/js/jquery.autosize.min.js"></script>
    <script src="/static/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
    <script src="/static/assets/js/jquery.maskedinput.min.js"></script>
    <script>
    $('.ibm_status_update').click(function () {
        var isok = confirm('即将是更新....大约需要20秒，请耐心等候！')
        if (isok){
            $.ajax({
            url: '{% url 'assets:ibm_status' %}',
            data: {'localpost':'localpost'},
            type: 'POST',
            success: function (data) {
                 if (data == 'updateok') {
                    //alert('更新成功!');
                    //location.reload(true);
                    window.location.reload();
                } else {
                    alert('更新失败!')
                }
            }
        })
        }

    })
    </script>
{##}
{% endblock %}

Django2YingOps/templates/assets/init.html
{% extends 'base.html' %}

{% block title %}
    YingOps-初始化资产
{% endblock %}

{% block zcopen %}class="active open"{% endblock %}
{% block initactive %}class="active"{% endblock %}

{% block content %}
    <div class="main-content">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try {
                    ace.settings.check('breadcrumbs', 'fixed')
                } catch (e) {
                }
            </script>

            <ul class="breadcrumb">
                <li>
                    <i class="icon-home home-icon"></i>
                    <a href="{% url 'index' %}">首页</a>
                </li>

                <li class="active">初始化资产</li>
            </ul><!-- .breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input"
                       autocomplete="off">
                <i class="icon-search nav-search-icon"></i>
            </span>
                </form>
            </div><!-- #nav-search -->
        </div>
        <div class="col-sm-5">
            <div class="widget-box">
                <div class="widget-header">
                    <h4>第一次初始化扫描/新增资产信息</h4>
                </div>

                <div class="widget-body">
                    <div class="widget-main no-padding">
                        <form action="{% url 'assets:assets_init' %}" method="post">
                            <!-- <legend>Form</legend> -->
                            <fieldset>
                                <div >网段: <span style="color: red">*支持以下方式 192.168.0.0/24或192.168.0.1或192.168.0.1-10</span></div>
                                <input type="text" name="nets"  placeholder="192.168.0.0/24" required>
                            </fieldset>
                            <fieldset>
                                <div>用户名: <span style="color: red">*登录系统的用户名如：root</span></div>
                                <input type="text" name="user_list" placeholder="Type something…" value="root" required>
                            </fieldset>
                            <fieldset>
{#                                <div>端口: <span style="color: red">*ssh端口号如：22，多个端口号，以；分隔符（不区分中英文符号）</span></div>#}
                                <div>端口: <span style="color: red">*ssh端口号：仅支持22号端口</span></div>
                                <input type="text" name="port_list" placeholder="请输入ssh端口号" value="22" required >
                            </fieldset>
                            <fieldset>
                                <div>密码: <span style="color: red">*可以输入多个密码，以；作为分隔符（不区分中英文符号）,建议提前写好复制进来</span></div>
                                <input id="passwd_list" type="password" name="passwd_list" placeholder="请输入密码" required>
                                <span id="look" class="glyphicon glyphicon-eye-open" title="点击显示/隐藏密码"></span>
                            </fieldset>
                            <div class="form-actions center">
                                <button type="submit" class="btn btn-sm btn-success">
                                    开始执行
                                    <i class="icon-arrow-right icon-on-right bigger-110"></i>
                                </button>
                                <span style="color: red">{{ msg }}</span>

                            </div>
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
<script>
    //显示或隐藏密码
    $('#look').click(function () {
        var type = $('#passwd_list').attr("type");
        if (type == "text") {
            $('#passwd_list').attr("type", "password");
            //attr：设置或返回被选元素的属性值。
            $(".look").children(".glyphicon").toggleClass("glyphicon-eye-open");
            $(".look").children(".glyphicon").toggleClass("glyphicon-eye-close");
            //toggleClass：如果存在（不存在）就删除（添加）一个类。
        } else {
            $('#passwd_list').attr("type", "text");
            $(".glyphicon").toggleClass("glyphicon-eye-open");
            $(".glyphicon").toggleClass("glyphicon-eye-close");
        }
    })
</script>
{% endblock %}

Django2YingOps/templates/assets/ipscan.html
{% extends 'base.html' %}

{% block title %}
    服务器操作
{% endblock %}
{% block fwqopen %}class="active open"{% endblock %}
{% block ipscan %}class="active"{% endblock %}
{% block content %}


<script type="text/javascript">
    try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
</script>


<div class="main-content">
    <ul class="breadcrumb">
            <li>
                <i class="icon-home home-icon"></i>
                <a href="{% url 'index' %}">首页</a>
            </li>

            <li>
                <a href="#">服务器操作</a>
            </li>
            <li class="active">IP扫描工具</li>
        </ul><!-- .breadcrumb -->
    <div class="page-content">
        <h3 class="header green"> IP扫描工具</h3>

        <div class="row">
            <div class="col-sm-6">
                <div class="widget-box">
                    <div class="widget-header">
                        <h4>IP扫描工具</h4>
                    </div>
                </div>
                <div class="widget-body">
                    <div class="widget-main" style="height: 400px;width: 80%">
                        <form action="{% url 'assets:assets_ipscan' %}" method="post">
                            {% csrf_token %}
                             <div class="col-sm-9">
                                 <label class="col-sm-3 control-label no-padding-right" for="ip"> 扫描指定网段： </label>
                                 <input type="text" name="ip" placeholder="192.168.5.0/24" class="col-xs-10 col-sm-5">
                                 <span>例如：192.168.5.0/24</span>
                            </div>

                            <button type="submit" name="networks" class="btn-primary btn-xs">开始扫描</button>


                        </form>
 <hr>

                         <form action="{% url 'assets:assets_ipscan' %}" method="post">
                             {% csrf_token %}

                             <div class="col-sm-9">
                                <label class="col-sm-3 control-label no-padding-right" for="ip"> 扫描指定IP： </label>
                                <input type="text" name="ip1" placeholder="192.168.5.155" class="col-xs-10 col-sm-5"><span>例如：192.168.5.155</span>
                            </div>
                            <button type="submit" name="network" class="btn-primary btn-xs">开始扫描</button>
                         </form>

                    </div>

                </div>
            </div>
            <div class="col-sm-4">
                <div class="widget-box">
                    <div class="widget-header">
                        <h4>返回结果</h4>
                    </div>
                </div>
                <div class="widget-body">
                    <div class="widget-main" style="height: 400px;width: 80%;overflow: auto">
                        {% for online_ip in status %}
                            {% if 'Online' in  online_ip %}
                                <div class="icon-circle green">{{ online_ip }} </div>
                            {% else %}
                                <div class="icon-circle">{{ online_ip }} </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div></div>
</div><!-- /.main-container -->



{% endblock %}

{% block js %}
    <script>
        function Dialog(serviceID, frmID)
        {
         var val = document.getElementById(serviceID).value;
         var isok = confirm(val);
         if(isok){
      		    document.getElementById(frmID).submit();
         }

        }
    </script>
{% endblock %}

Django2YingOps/templates/assets/webssh.html
{% extends 'base.html' %}

{% block title %}
    YingOps-webssh
{% endblock %}

{% block fwqopen %}class="active open"{% endblock %}
{% block websshactive %}class="active"{% endblock %}

{% block content %}
    <div class="main-content">
        <!-- 导航标签及顶部搜索功能 -->
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try {
                    ace.settings.check('breadcrumbs', 'fixed')
                } catch (e) {
                }
            </script>

            <ul class="breadcrumb">
                <li>
                    <i class="icon-home home-icon"></i>
                    <a href="{% url 'index' %}">首页</a>
                </li>

                <li>
                    <a href="#">资产信息</a>
                </li>
                <li class="active">WebSsh</li>
            </ul><!-- .breadcrumb -->

        </div>
        <iframe src="{{ url }}{{ hostname }}" width="1200" height="800"></iframe>
        <form action="{% url 'assets:assets_webssh' %}" method="post">
            <button class="btn-primary btn-sm" name="startwebssh" type="submit">启动webssh</button>

            <button class="btn-primary btn-sm" name="stopwebssh" type="submit">停止webssh</button>

        </form>
    </div>

{% endblock %}