Django2YingOps/Django2YingOps/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from Django2YingOps.settings import MEDIA_ROOT

import xadmin
from users.views import *
from assets.views import *

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    # include urls
    path('users/',include('users.urls')),
    path('assets/',include('assets.urls')),

    path('',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('index/',IndexView.as_view(),name='index'),
    path('register/',RegisterView.as_view(),name='register'),
    path('forget/',ForgetPwdView.as_view(),name='forget'),

    #配置上传文件的访问处理函数
    re_path('media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),
]

Django2YingOps/apps/users/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from users.views import *

app_name = 'users'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('info/', UserInfo.as_view(),name='user_info'),
    path('modify/', ModifyPwd.as_view(),name='user_modifypwd'),
]

Django2YingOps/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
# Create your models here.


class UserProfile(AbstractUser):
    phone = models.CharField(max_length=11,default='',verbose_name=u'手机号')
    birthday = models.DateField(null=True, blank=True,verbose_name=u'生日')
    gender = models.CharField(max_length=6, choices=(("male", u"男"), ("female", "女")), default="male")
    image = models.ImageField(upload_to="image/%Y/%m", default=u"image/2020/03/touxiang.jpg", max_length=100)
    email = models.EmailField(max_length=20,null=True, blank=True,verbose_name=u'邮箱')

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=20, verbose_name=u"验证码")
    email = models.EmailField(max_length=50, verbose_name=u"邮箱")
    send_type = models.CharField(verbose_name=u"验证码类型", choices=(("register",u"注册"),("forget",u"找回密码"), ("update_email",u"修改邮箱")), max_length=30)
    send_time = models.DateTimeField(verbose_name=u"发送时间", default=timezone.now)

    class Meta:
        verbose_name = u"邮箱验证码"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}({1})'.format(self.code, self.email)

Django2YingOps/apps/users/forms.py
from django import forms
from .models import *


class UserProfileForm(forms.Form):
    username = forms.CharField(required=True,max_length=20,min_length=5)
    password = forms.CharField(required=True,max_length=20,min_length=5)


class ModifyPwdForm(forms.Form):
    password1 = forms.CharField(required=True,min_length=5)
    password2 = forms.CharField(required=True,min_length=5)


class RegisterForm(forms.Form):
    reg_email = forms.EmailField(required=True)
    reg_username = forms.CharField(required=True,min_length=5)
    reg_password = forms.CharField(required=True,min_length=5)
    rep_password = forms.CharField(required=True,min_length=5)
    phone = forms.CharField(required=True,min_length=11)

Django2YingOps/apps/users/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views.generic import View
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.hashers import make_password
from django.db.models import Q

from utils.mixin_util import LoginRequiredMixin
from .forms import *
from assets.models import AssetsInfo


class IndexView(LoginRequiredMixin, View):
    """
    首页展示
    """

    def get(self, request):
        linux_count = AssetsInfo.objects.all().count()
        windows_count = 0
        switch_count = 0
        return render(request, 'index.html', locals())


class LoginView(View):
    """
    登录系统
    """

    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        userprofile_form = UserProfileForm(request.POST)
        if userprofile_form.is_valid():
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return render(request, 'index.html', locals())
            return render(request, 'login.html', {'msg': '登录：用户名或者密码错误'})
        return render(request, 'login.html', {'userprofile_form': userprofile_form})


class LogoutView(View):
    """
    登出系统
    """

    def get(self, request):
        logout(request)
        return render(request, 'login.html')


class UserInfo(LoginRequiredMixin, View):
    """
    用户信息
    """

    def get(self, request):
        userprofile = UserProfile.objects.all()
        return render(request, 'users/info.html', locals())

    def post(self, request):
        pass


class ModifyPwd(LoginRequiredMixin, View):
    """
    修改用户密码
    """

    def post(self, request):
        modifypwd_form = ModifyPwdForm(request.POST)
        if modifypwd_form.is_valid():
            pwd1 = request.POST.get("password1", "")
            pwd2 = request.POST.get("password2", "")
            userprofile = UserProfile.objects.get(username=request.user)
            if pwd1 != pwd2:
                msg = ' 密码不一致，请重新输入！'
                return render(request, 'users/info.html', locals())
            userprofile.password = make_password(pwd1)
            userprofile.save()
            return render(request, 'users/info.html', locals())
        return render(request, 'users/info.html', locals())


class RegisterView(View):
    """
    注册用户
    """

    def post(self, request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user = UserProfile()
            reg_email = request.POST.get('reg_email')
            username = request.POST.get('reg_username')
            phone = request.POST.get('phone')
            reg_password = request.POST.get('reg_password')
            rep_password = request.POST.get('rep_password')
            if reg_password != rep_password:
                msg = '注册用户：密码不一致，请重新输入！'
                return render(request, 'login.html', locals())
            user.email = reg_email
            user.phone = phone
            user.password = make_password(reg_password)
            if UserProfile.objects.filter(username=username):
                msg = "注册用户：该用户'{0}'已经存在，请重新输入！".format(username)
                return render(request, 'login.html', locals())
            user.username = username
            user.save()
            msg = '恭喜您{0}，注册成功，可以进行登录！'.format(username)
            return render(request, 'login.html', locals())
        else:
            return render(request, 'login.html', locals())


class ForgetPwdView(View):
    def post(self, request):
        email = request.POST.get('forgetpwd', '')

        if UserProfile.objects.filter(Q(username=email) | Q(email=email)):
            user = UserProfile.objects.get(Q(username=email) | Q(email=email))
            user.password = make_password('123456')
            user.save()
            msg = '忘记密码：密码重置成功，密码为：123456'
            return render(request, 'login.html', locals())
        else:
            msg = "忘记密码：系统中没有该用户'{0}'".format(email)
            return render(request, 'login.html', locals())

Django2YingOps/templates/users/info.html
{% extends 'base.html' %}
{% block title %}用户信息页面{% endblock %}
{% block css %}{% endblock %}
{% block content %}
    <div class="main-content">
        <div class="page-content">
            <div class="row col-xs-12">
                <div class="col-sm-3 center">
                    <div class="space space-4"></div>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off"
                          method="post" action="" target='frameFile'>
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="300" height="300" class="js-img-show" id="avatarShow"
                                     src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                            </span>
{#                            <span class="fl upload-inp-box" style="margin-left:70px;">#}
{#                                <span class="btn btn-primary" id="jsAvatarBtn">修改头像</span>#}
{#                                <input type="file" name="image" id="avatarUp" class="js-img-up" style="display: none"/>#}
{#                            </span>#}
                        </label>
                        {% csrf_token %}
                    </form>
                </div><!-- /span -->
                <div class="col-sm-9">
                    <h4 class="blue">
                        <span class="middle">{{ request.user.username }}</span>

                        <span class="label label-purple arrowed-in-right">
                            <i class="icon-circle smaller-80 align-middle"></i>
                            online
                        </span>
                    </h4>

                    <div class="profile-user-info">
                        <div class="profile-info-row">
                            <div class="profile-info-name"> 用户名</div>

                            <div class="profile-info-value">
                                <span>{{ request.user.username }}</span>
                            </div>
                        </div>
                        <div class="profile-info-row">
                            <div class="profile-info-name"> 性别</div>

                            <div class="profile-info-value">
                                <span>{% if request.user.gender == 'male' %}男{% else %}女{% endif %}</span>
                            </div>
                        </div>
                        <div class="profile-info-row">
                            <div class="profile-info-name"> 生日</div>

                            <div class="profile-info-value">
                                <span>{{ request.user.birthday }}</span>
                            </div>
                        </div>
                        <div class="profile-info-row">
                            <div class="profile-info-name"> 手机号</div>

                            <div class="profile-info-value">
                                <span>{{ request.user.phone }}</span>
                            </div>
                        </div>
                        <div class="profile-info-row">
                            <div class="profile-info-name"> 邮箱</div>

                            <div class="profile-info-value">
                                <span>{{ request.user.email }}</span>
                            </div>
                        </div>
                        <div class="profile-info-row">
                            <div class="profile-info-name"> 是否管理员</div>

                            <div class="profile-info-value">
                                <span>{% if request.user.is_superuser|stringformat:'i' == '1' %}是 <a href="/xadmin">后台管理</a>{% else %}
                                    否{% endif %}</span>
                            </div>
                        </div>
                        <div class="profile-info-row">
                            <div class="profile-info-name"> 上次登录</div>

                            <div class="profile-info-value">
                                <span>{{ request.user.last_login }}</span>
                            </div>
                        </div>
{#                        <div class="profile-info-row">#}
{#                            <div class="profile-info-name"> 注册时间</div>#}
{##}
{#                            <div class="profile-info-value">#}
{#                                <span>{{ request.user.date_joined }}</span>#}
{#                            </div>#}
{#                        </div>#}
                        <div class="profile-info-row">
                            <div class="profile-info-name"> 密码</div>

                            <div class="profile-info-value" >
                                <button class="btn btn-sm" id="modify">修改密码</button>
                                <span style="color:red">{{modifypwd_form.errors}}{{ msg }}</span>
                            </div>
                        </div>
                    </div>

                    <div class="hr hr-8 dotted"></div>

                    <div id="modify_password" class="widget-box hidden">
                        <div class="widget-header">
                            <h4>修改密码</h4>
                        </div>
                        <div class="widget-body" >
                            <div class="widget-main">
                                <form class="form-inline" method="post" action="{% url 'users:user_modifypwd' %}">
                                    <label>密码：</label>
                                    <input type="password" class="input-large" placeholder="Password1" name="password1" required>
                                    <label>确认密码：</label>
                                    <input type="password" class="input-large" placeholder="Password2" name="password2" required>
                                    <button type="submit" class="btn btn-danger btn-sm">
                                        <i class="icon-key bigger-110"></i>
                                        确认修改
                                    </button>
                                    {% csrf_token %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                </div>
            </div>

        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        {#显示和隐藏修改密码框#}
        $("#modify").click(function () {
            if($("#modify_password").hasClass('hidden')){
                $("#modify_password").removeClass('hidden')
            }else{
                $("#modify_password").addClass('hidden')
            };
        })
    </script>
{% endblock %}